export const SAVE_ENTRY_REQUEST = 'SAVE_ENTRY_REQUEST';
export const FETCH_ENTRY_REQUEST = 'FETCH_ENTRY_REQUEST';
export const UPDATE_ENTRY_REQUEST = 'UPDATE_ENTRY_REQUEST';
export const ENTRY_SUCCESS = 'ENTRY_SUCCESS';
export const ENTRY_FAILURE = 'ENTRY_FAILURE';